### ISSUE TITLE
Passing black and white mask as label throws an error

### ISSUE THREAD

**Issue by arjunpmm** [GeorgeSeif/Semantic-Segmentation-Suite#107] opened 2018-09-28 02:37 UTC
### Information

- **Command line arguments: --num_epochs 20 --checkpoint_step 2 --validation_step 5 --dataset Roof_detection --crop_height  200 --crop_width 200 --batch_size 4 --num_val_images 500 --h_flip False --v_flip False --model MobileUNet --frontend MobileNetV2**
- **Have you written any custom code?: No**
- **What have you done to try and solve this issue?:** tried to look into the opencv module to make sense of the function `cvtColor`, look on stackoverflow for similar problems
- **TensorFlow version?**: 1.10.0

### Problem description

Opencv `cv2.cvtColor(cv2.imread(path, -1), cv2.COLOR_BGR2RGB)` throws an unknown error when a black and white mask is passed. This function is used in the `load_image` function of `utils.py`

Please see below for example of an image passed. It's part of the train_labels folder.

![11](https://user-images.githubusercontent.com/1721946/46135731-72a3c680-c278-11e8-89af-fa744a38d33d.png)

### Source code / logs
The following is the error:
```Traceback (most recent call last):
  File "D:/Projects/Semantic-Segmentation-Suite/train.py", line 176, in <module>
    output_image = utils.load_image(train_output_names[id])
  File "D:\Projects\Semantic-Segmentation-Suite\utils\utils.py", line 45, in load_image
    image = cv2.cvtColor(cv2.imread(path, -1), cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(3.4.3) d:\build\opencv\opencv-3.4.3\modules\imgproc\src\color.hpp:255: error: (-2:Unspecified error) in function '__cdecl cv::CvtHelper<struct cv::Set<3,4,-1>,struct cv::Set<3,4,-1>,struct cv::Set<0,2,5>,2>::CvtHelper(const class cv::_InputArray &,const class cv::_OutputArray &,int)'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 1
```

**Comment by GeorgeSeif** [comment] 2018-09-29 12:10
Well since your images are not in colour, a colour conversion function to RGB won't work!

Closing since this is not a bug or feature request.

**Closed by GeorgeSeif** 2018-09-29 12:10 UTC
